#!/usr/bin/env python
# Toggle Output #1

import RPi.GPIO as GPIO
import time
import datetime

GPIO.setwarnings(False)

output_pin_1 = 17
output_pin_2 = 18
	
GPIO.setmode(GPIO.BCM)

GPIO.setup(output_pin_2, GPIO.OUT)
GPIO.output(output_pin_2, True)

GPIO.setup(output_pin_1, GPIO.OUT)
GPIO.output(output_pin_1, False)
time.sleep(1)
GPIO.output(output_pin_1, True) 
print("done")

# Write time to file
with open("/home/pi/toggle_switch.log", "a") as logf:
	logf.write(str(datetime.datetime.now()) + "\n")
